# Matrix Factorization

In [47]:
import pandas as pd
import numpy as np
import json
import seaborn as sns
import matplotlib.pyplot as plt

## Preprocessing

In [49]:
f = open('challenge_set.json','r')
data = json.loads(f.read())
df = pd.json_normalize(data,record_path=['playlists'],meta=['date'])

tracks = df['tracks']

def new_columns(key,col = tracks,empty = ['Empty']):
    info = []
    for i in col:
        if i==[]:
            info.append(empty)
        else:
            lst = list()
            for j in i:
                lst.append(j[key])
            info.append(lst)
    return info

keys = ['track_name','artist_name','track_uri','artist_uri','album_uri','duration_ms','album_name']
for k in keys:
    df[k] = new_columns(k)

In [50]:
def unique_tracks(playlist):
    ret_lst = list()
    for i in playlist:
        for j in i:
            if j not in ret_lst:
                ret_lst.append(j)
    return ret_lst

In [51]:
np.random.seed(1)
arr = np.random.choice([i for i in range(1000)],200,replace=False)
arr

array([507, 818, 452, 368, 242, 929, 262, 810, 318,  49, 446, 142, 968,
       345, 971, 133, 104,   6, 600, 496, 702, 472, 598, 502, 433, 119,
       108, 647, 589, 374, 910, 718, 744, 494, 404, 274,  78, 721, 644,
       614, 872, 691,  90, 101,  94, 577, 537,  41, 453, 995, 713,  34,
       639,  35, 148, 455, 885, 677, 486, 685, 307, 238, 395, 734, 822,
       812, 464, 816, 528,  17, 709, 370, 241, 964, 457,  65, 191, 838,
       331, 638, 255, 742, 756, 757, 951, 992, 463, 843, 573, 527, 654,
       189, 517, 956, 414, 671, 559, 593, 258, 154, 335,  13, 911, 156,
       428, 824, 267, 538, 236, 944, 479, 785, 950,  59, 868, 175, 711,
       449, 120, 794, 180, 311,   3, 194, 437, 683, 799, 746, 625, 692,
       551, 248, 659,   2, 997, 860, 776, 857, 358, 769,  73, 117, 938,
       535, 111, 509, 512, 916, 555, 552, 354, 970,   8, 581,  56, 576,
       705, 651,  84, 228, 159, 205, 125, 688, 887, 473, 244, 597, 797,
       195, 202,  81, 484, 443, 578, 201, 186, 516, 821, 967, 21

In [52]:
df2 = pd.DataFrame()
for i in range(9):
    for a in arr[:100]:
        df2 = df2.append(df.iloc[a+1000*(i+1)])

/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.con

/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.con

/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.con

/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.con

/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.con

/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.con

/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.con

/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.con

/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.con

/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.con

/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.con

/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.con

/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.con

/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.con

/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.con

/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.con

/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.con

/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.iloc[a+1000*(i+1)])
/tmp/ipykernel_607/2067360853.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.con

In [53]:
true = pd.DataFrame()
for a in arr[100:]:
    true = true.append(df.iloc[a+7000])

/tmp/ipykernel_607/1264129448.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  true = true.append(df.iloc[a+7000])
/tmp/ipykernel_607/1264129448.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  true = true.append(df.iloc[a+7000])
/tmp/ipykernel_607/1264129448.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  true = true.append(df.iloc[a+7000])
/tmp/ipykernel_607/1264129448.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  true = true.append(df.iloc[a+7000])
/tmp/ipykernel_607/1264129448.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  t

/tmp/ipykernel_607/1264129448.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  true = true.append(df.iloc[a+7000])
/tmp/ipykernel_607/1264129448.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  true = true.append(df.iloc[a+7000])
/tmp/ipykernel_607/1264129448.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  true = true.append(df.iloc[a+7000])
/tmp/ipykernel_607/1264129448.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  true = true.append(df.iloc[a+7000])
/tmp/ipykernel_607/1264129448.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  t

/tmp/ipykernel_607/1264129448.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  true = true.append(df.iloc[a+7000])
/tmp/ipykernel_607/1264129448.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  true = true.append(df.iloc[a+7000])
/tmp/ipykernel_607/1264129448.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  true = true.append(df.iloc[a+7000])
/tmp/ipykernel_607/1264129448.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  true = true.append(df.iloc[a+7000])
/tmp/ipykernel_607/1264129448.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  t

In [54]:
cols = df.columns
cols

Index(['name', 'num_holdouts', 'pid', 'num_tracks', 'tracks', 'num_samples',
       'date', 'track_name', 'artist_name', 'track_uri', 'artist_uri',
       'album_uri', 'duration_ms', 'album_name'],
      dtype='object')

In [55]:
append_cols = ['track_name','artist_name','track_uri','artist_uri','album_uri']

In [56]:
def takeout(columns,seed,data):
    np.random.seed(seed)
    ret_lst = list()
    arr = np.random.choice([i for i in range(100)],50,replace=False)
    for c in columns:
        col = list()
        for i in data.index:
            lst = list()
            for a in arr:
                lst.append(data[c][i][a])
            col.append(lst)
        ret_lst.append(col)
    return ret_lst

In [59]:
lst = takeout(append_cols,100,true)

In [60]:
copy = pd.DataFrame.copy(true)
for i in range(len(append_cols)):
    copy[append_cols[i]]=lst[i]

In [63]:
df2 = df2.append(copy)

/tmp/ipykernel_607/3415438193.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(copy)


In [64]:
subset_tracks = unique_tracks(df2['track_uri'])
subset_artist = unique_tracks(df2['artist_uri'])

In [68]:
def make_dict(column,values,full_track,data_frame):
    dictionary = dict()
    for track in full_track:
        for index in data_frame.index:
            if track in data_frame[column][index]:
                i = data_frame[column][index].index(track)
                dictionary[track]=data_frame[values][index][i]
                break
    return dictionary

In [69]:
track_artist_uri = make_dict('track_uri','artist_uri',subset_tracks,df2)

In [70]:
track = make_dict('track_uri','track_name',subset_tracks,df2)

In [71]:
artist = make_dict('artist_uri','artist_name',subset_artist,df2)

In [65]:
def create_ratings(user,tracks,track_col='track_uri',art_col='artist_uri'):
    lst = list()
    for track in tracks:
        if track in user[track_col]:
            lst.append((user[art_col].count(track_artist_uri[track]))/len(user[art_col]))
        else:
            lst.append(0.0)
    return lst

In [66]:
def create_matrix(data_frame,tracks,track_col='track_uri',art_col='artist_uri'):
    lst = list()
    for index in range(len(data_frame)):
        lst.append(create_ratings(data_frame.iloc[index],tracks,track_col,art_col))
    arr = np.array(lst)
    return arr

In [72]:
mat = create_matrix(df2,subset_tracks,'track_uri','artist_uri')

In [73]:
mat

array([[0.2 , 0.6 , 0.6 , ..., 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , ..., 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , ..., 0.  , 0.  , 0.  ],
       ...,
       [0.  , 0.  , 0.  , ..., 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , ..., 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , ..., 0.08, 0.08, 0.04]])

## Matrix Factorization

In [42]:
def matrix_factorization(R, P, Q, K, steps = 5000, alpha = 0.001, beta = 0.01):
    
    Q = Q.T
    
    for step in range(steps):
        for i in range(len(R)):
            for j in range(len(R[i])):
                if R[i][j]>0:
                    eij = R[i][j] - np.dot(P[i,:],Q[:,j])
                    
                    for k in range(K):
                        P[i][k] = P[i][k]+alpha*(2*eij*Q[k][j]-beta*P[i][k])
                        Q[k][j] = Q[k][j]+alpha*(2*eij*P[i][k]-beta*Q[k][j])
        eR = np.dot(P,Q)
        e = 0
        for i in range(len(R)):
            for j in range(len(R[i])):
                if R[i][j]>0:
                    e = e + pow(R[i][j]-np.dot(P[i,:],Q[:,j]),2)
        if e<0.01:
            break
    return P, Q.T

In [78]:
NoOfUsers = len(mat)
NoOfItems = len(mat[0])
K=10

In [79]:
P = np.random.rand(NoOfUsers,K)
Q = np.random.rand(NoOfItems,K)
P,Q

(array([[0.55773903, 0.54018669, 0.82571104, ..., 0.59890999, 0.98428619,
         0.01353842],
        [0.8990689 , 0.26791823, 0.91719194, ..., 0.49829878, 0.40327137,
         0.762784  ],
        [0.37315246, 0.16042262, 0.86749936, ..., 0.54085234, 0.61283844,
         0.65695099],
        ...,
        [0.49239826, 0.41534091, 0.60492135, ..., 0.20285871, 0.47340151,
         0.68093667],
        [0.05427348, 0.34124126, 0.79199282, ..., 0.44328203, 0.47922655,
         0.56390995],
        [0.34311789, 0.49504886, 0.15548341, ..., 0.15588956, 0.2005533 ,
         0.39341072]]),
 array([[0.96143784, 0.4742875 , 0.74783795, ..., 0.79209166, 0.01239033,
         0.84873123],
        [0.892264  , 0.11068058, 0.845815  , ..., 0.21098721, 0.49213745,
         0.66732131],
        [0.06740716, 0.85243927, 0.68275706, ..., 0.91542627, 0.29334541,
         0.19930997],
        ...,
        [0.08519262, 0.49832964, 0.37413805, ..., 0.17581424, 0.69311031,
         0.27998482],
        [0.9

In [85]:
%%time
nP,nQ = matrix_factorization(mat,P,Q,K,steps=100,alpha=0.01)
nP, nQ

CPU times: user 20min 48s, sys: 1min 11s, total: 22min
Wall time: 19min 1s


(array([[ 0.04872319,  0.02398115,  0.33732819, ...,  0.25797982,
          0.63951862, -0.49164517],
        [ 0.7064297 , -0.15377211,  0.47571384, ...,  0.12910334,
          0.11589423,  0.50227919],
        [-0.01960529, -0.14420553,  0.55664222, ...,  0.32665095,
          0.37433186,  0.41825893],
        ...,
        [ 0.03679279,  0.08932015,  0.06545334, ..., -0.00691501,
          0.00104393, -0.01353536],
        [ 0.01510501, -0.005093  ,  0.01020104, ...,  0.00238118,
          0.0137711 ,  0.00248868],
        [ 0.01601549,  0.01065811,  0.02698858, ...,  0.02980012,
          0.01429467,  0.01259186]]),
 array([[ 0.90376442,  0.43003163,  0.6991887 , ...,  0.75130282,
         -0.00312209,  0.78903509],
        [ 0.80262602,  0.04509233,  0.69193011, ...,  0.11217411,
          0.27793942,  0.71953451],
        [ 0.03357549,  0.79666263,  0.60448319, ...,  0.84719823,
          0.19906303,  0.21727505],
        ...,
        [ 0.08494234,  0.48269571,  0.37003325, ...,  

In [86]:
mat

array([[0.2 , 0.6 , 0.6 , ..., 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , ..., 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , ..., 0.  , 0.  , 0.  ],
       ...,
       [0.  , 0.  , 0.  , ..., 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , ..., 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , ..., 0.08, 0.08, 0.04]])

In [87]:
nR = np.dot(nP,nQ.T)
nR

array([[0.20376151, 0.5963027 , 0.59456518, ..., 0.79511597, 1.03238286,
        0.9721865 ],
       [1.59933377, 1.73582216, 0.67019312, ..., 0.79318396, 1.29930177,
        1.36510907],
       [0.86484883, 0.57656473, 0.63743492, ..., 0.39408965, 0.58310166,
        0.62706599],
       ...,
       [0.09372045, 0.05543926, 0.09382268, ..., 0.04725044, 0.1177736 ,
        0.05986185],
       [0.02915405, 0.03998475, 0.01596702, ..., 0.02447569, 0.03214112,
        0.04156438],
       [0.0754628 , 0.05436432, 0.06236605, ..., 0.04172843, 0.07088623,
        0.052495  ]])

In [93]:
df2.iloc[900]['track_uri']

['spotify:track:1MzlQlMCHU4zSyHjVGbMln',
 'spotify:track:2g5cChGDcrjtpRVGA7q4Eh',
 'spotify:track:2rh81n7fCzM1Th0U6gDdfa',
 'spotify:track:2hKdd3qO7cWr2Jo0Bcs0MA',
 'spotify:track:3dPKGlKVq3dRrFCAnOBsQW',
 'spotify:track:1q74TesvRCIo5RvJM5B84F',
 'spotify:track:42IXcixHs7xsMmv5TKzoiG',
 'spotify:track:4yugZvBYaoREkJKtbG08Qr',
 'spotify:track:615XzGXe72YUjagvkMmEFi',
 'spotify:track:3sBfItjYrLgKrCPIZndhc6',
 'spotify:track:5J3RechBID8luzPkCO63ZW',
 'spotify:track:4BGJSbB5rAcg4pNzD4gfxU',
 'spotify:track:2kI0ROp8nVlZNIqZnRori9',
 'spotify:track:0KwQeQLWbtLa4qlYeWvO0L',
 'spotify:track:7rMLf4n5vm81dlbDu15KSC',
 'spotify:track:2H6CBRyOXIHzajVrMGen3b',
 'spotify:track:1SlJJV2bvFO6Zf6jfPE5ro',
 'spotify:track:6XCofYuJfYQDykaGvH98Ev',
 'spotify:track:4ocbH5ZJqajZIpUrqRUoue',
 'spotify:track:22RxilGS5NSRe2ELlyKeTi',
 'spotify:track:4LQzFOJgbwIuaydxIFWB9Q',
 'spotify:track:6xleIePy9XfIOV8ksoKlKx',
 'spotify:track:13U48U3VZb2iufNNvSTZLs',
 'spotify:track:7wMq5n8mYSKlQIGECKUgTX',
 'spotify:track:

In [103]:
list(set(true.iloc[0]['track_uri']).difference(df2.iloc[900]['track_uri']))

['spotify:track:05oETzWbd4SI33qK2gbJfR',
 'spotify:track:0BgbobvykXxEvxo2HhCuvM',
 'spotify:track:2HO2bnoMrpnZUbUqiilLHi',
 'spotify:track:7zmMQkL7IYtzlA8NkrA68k',
 'spotify:track:5ihS6UUlyQAfmp48eSkxuQ',
 'spotify:track:6m9nn91t8kfuWoXvYu9i2G',
 'spotify:track:7DtIdJ2oeqBIeX8muz8ybI',
 'spotify:track:1G8jae4jD8mwkXdodqHsBM',
 'spotify:track:5TSZAgNUBDfLizM9D2J2Ll',
 'spotify:track:5EjZXJ4nVpw7uI6eso1SFS',
 'spotify:track:3FvCy00Wz75HmhlXPMmnOx',
 'spotify:track:3TQxkQsyJS03EUwl02Qaub',
 'spotify:track:3yvlcIteooc31cPjyWPTw1',
 'spotify:track:2W6PNGCN4PGwPMf1jYazL4',
 'spotify:track:1aE5FWmkQJuT2SWLg3X8VJ',
 'spotify:track:3S0OXQeoh0w6AY8WQVckRW',
 'spotify:track:7FsDMr29CRPvSJIgxCGmtf',
 'spotify:track:1bqi9YEdZweX9H6JuSQ6Qw',
 'spotify:track:75JFxkI2RXiU7L9VXzMkle',
 'spotify:track:15twB7zTglmu0Bg8gW4Mrm',
 'spotify:track:6iz58z2LC8uHL3H2aiwX6I',
 'spotify:track:3gADeIKXuMPSrTa0qKc6i0',
 'spotify:track:3SktMqZmo3M9zbB7oKMIF7',
 'spotify:track:2EWpa5XnAuSn0sIkSSIhYk',
 'spotify:track:

In [105]:
true_tracks = list(true['track_uri'])

In [167]:
df_predict = pd.DataFrame(nR,columns=subset_tracks)

In [204]:
def precision(temp,true):
    count = 0
    num_rec_tracks = 0
    for user in range(len(temp)):
        num_rec_tracks+=len(temp[user])
        for track in temp[user]:
            if track in true[user]:
                count+=1
    return count/num_rec_tracks

In [209]:
lst_of_recommendations = list()
for i in range(900,1000):
    temp = list(df_predict.iloc[i].sort_values(ascending=False).index)
    temp = temp[:50]
    temp = list(set(temp).difference(df2.iloc[i]['track_uri']))
    lst_of_recommendations.append(temp)

In [210]:
precision(lst_of_recommendations,true_tracks)

0.0014008405043025814